# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.file4 import File4
from ..types.processor_id import ProcessorId
from ..types.processor_type import ProcessorType
from .raw_client import AsyncRawProcessorEndpointsClient, RawProcessorEndpointsClient
from .types.get_batch_processor_runs_id_response import GetBatchProcessorRunsIdResponse
from .types.get_processor_runs_id_response import GetProcessorRunsIdResponse
from .types.get_processors_id_versions_response import GetProcessorsIdVersionsResponse
from .types.get_processors_processor_id_versions_processor_version_id_response import (
    GetProcessorsProcessorIdVersionsProcessorVersionIdResponse,
)
from .types.post_processor_runs_response import PostProcessorRunsResponse
from .types.post_processors_id_publish_request_release_type import PostProcessorsIdPublishRequestReleaseType
from .types.post_processors_id_publish_response import PostProcessorsIdPublishResponse
from .types.post_processors_id_response import PostProcessorsIdResponse
from .types.post_processors_response import PostProcessorsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProcessorEndpointsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProcessorEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProcessorEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProcessorEndpointsClient
        """
        return self._raw_client

    def run_processor(
        self,
        *,
        processor_id: ProcessorId,
        file: typing.Optional[File4] = OMIT,
        raw_text: typing.Optional[str] = OMIT,
        version: typing.Optional[str] = OMIT,
        priority: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostProcessorRunsResponse:
        """
        Run processors (extraction, classification, splitting, etc.) on a given document

        Parameters
        ----------
        processor_id : ProcessorId

        file : typing.Optional[File4]

        raw_text : typing.Optional[str]
            The raw text content of the file. This is included for all file types if the `rawText` query parameter is set to `true` in the endpoint request.

        version : typing.Optional[str]

        priority : typing.Optional[int]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            An optional object that can be passed in to identify the run of the document processor. It will be returned back to you in the response and webhooks.

        config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostProcessorRunsResponse
            Successfully created processor run

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.processor_endpoints.run_processor(processor_id='processorId', )
        """
        _response = self._raw_client.run_processor(
            processor_id=processor_id,
            file=file,
            raw_text=raw_text,
            version=version,
            priority=priority,
            metadata=metadata,
            config=config,
            request_options=request_options,
        )
        return _response.data

    def get_processor_run(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetProcessorRunsIdResponse:
        """
        Retrieve details about a specific processor run, including its status, outputs, and any edits made during review

        Parameters
        ----------
        id : str
            The unique identifier of the processor run to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProcessorRunsIdResponse
            Successfully retrieved processor run

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.processor_endpoints.get_processor_run(id='id', )
        """
        _response = self._raw_client.get_processor_run(id, request_options=request_options)
        return _response.data

    def create_processor(
        self,
        *,
        name: str,
        type: ProcessorType,
        clone_processor_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostProcessorsResponse:
        """
        Create a new processor in Extend, optionally cloning from an existing processor

        Parameters
        ----------
        name : str
            The name of the new processor

        type : ProcessorType

        clone_processor_id : typing.Optional[str]
            The ID of an existing processor to clone. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostProcessorsResponse
            Successfully created processor

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.processor_endpoints.create_processor(name='name', type="EXTRACT", )
        """
        _response = self._raw_client.create_processor(
            name=name, type=type, clone_processor_id=clone_processor_id, request_options=request_options
        )
        return _response.data

    def get_processor_version(
        self, processor_id: str, processor_version_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetProcessorsProcessorIdVersionsProcessorVersionIdResponse:
        """
        Retrieve a specific version of a processor in Extend

        Parameters
        ----------
        processor_id : str
            The ID of the processor. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        processor_version_id : str
            The ID of the specific processor version to retrieve. The ID will start with "dpv_".

            Example: `"dpv_QYk6jgHA_8CsO8rVWhyNC"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProcessorsProcessorIdVersionsProcessorVersionIdResponse
            Successfully retrieved processor version

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.processor_endpoints.get_processor_version(processor_id='processorId', processor_version_id='processorVersionId', )
        """
        _response = self._raw_client.get_processor_version(
            processor_id, processor_version_id, request_options=request_options
        )
        return _response.data

    def list_processor_versions(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetProcessorsIdVersionsResponse:
        """
        Retrieve all versions of a specific processor in Extend, including the current draft version

        Parameters
        ----------
        id : str
            The ID of the processor to retrieve versions for. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProcessorsIdVersionsResponse
            Successfully retrieved processor versions

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.processor_endpoints.list_processor_versions(id='id', )
        """
        _response = self._raw_client.list_processor_versions(id, request_options=request_options)
        return _response.data

    def publish_processor_version(
        self,
        id: str,
        *,
        release_type: PostProcessorsIdPublishRequestReleaseType,
        description: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostProcessorsIdPublishResponse:
        """
        Publish a new version of an existing processor in Extend

        Parameters
        ----------
        id : str
            The ID of the processor to publish a new version for. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        release_type : PostProcessorsIdPublishRequestReleaseType
            The type of release for this version

        description : typing.Optional[str]
            A description of the changes in this version

        config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Optionally supply a config object for this version of the processor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostProcessorsIdPublishResponse
            Successfully published processor version

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.processor_endpoints.publish_processor_version(id='id', release_type="major", )
        """
        _response = self._raw_client.publish_processor_version(
            id, release_type=release_type, description=description, config=config, request_options=request_options
        )
        return _response.data

    def get_batch_processor_run(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetBatchProcessorRunsIdResponse:
        """
        Retrieve details about a batch processor run, including evaluation runs

        Parameters
        ----------
        id : str
            The unique identifier of the batch processor run to retrieve. The ID will start with "bpr_".

            Example: `"bpr_Xj8mK2pL9nR4vT7qY5wZ"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBatchProcessorRunsIdResponse
            Successfully retrieved batch processor run

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.processor_endpoints.get_batch_processor_run(id='id', )
        """
        _response = self._raw_client.get_batch_processor_run(id, request_options=request_options)
        return _response.data

    def update_processor(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostProcessorsIdResponse:
        """
        Update an existing processor in Extend

        Parameters
        ----------
        id : str
            The ID of the processor to update. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        name : typing.Optional[str]
            The new name for the processor

        config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            The new configuration for the processor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostProcessorsIdResponse
            Successfully updated processor

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.processor_endpoints.update_processor(id='id', )
        """
        _response = self._raw_client.update_processor(id, name=name, config=config, request_options=request_options)
        return _response.data


class AsyncProcessorEndpointsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProcessorEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProcessorEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProcessorEndpointsClient
        """
        return self._raw_client

    async def run_processor(
        self,
        *,
        processor_id: ProcessorId,
        file: typing.Optional[File4] = OMIT,
        raw_text: typing.Optional[str] = OMIT,
        version: typing.Optional[str] = OMIT,
        priority: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostProcessorRunsResponse:
        """
        Run processors (extraction, classification, splitting, etc.) on a given document

        Parameters
        ----------
        processor_id : ProcessorId

        file : typing.Optional[File4]

        raw_text : typing.Optional[str]
            The raw text content of the file. This is included for all file types if the `rawText` query parameter is set to `true` in the endpoint request.

        version : typing.Optional[str]

        priority : typing.Optional[int]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            An optional object that can be passed in to identify the run of the document processor. It will be returned back to you in the response and webhooks.

        config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostProcessorRunsResponse
            Successfully created processor run

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.processor_endpoints.run_processor(processor_id='processorId', )
        asyncio.run(main())
        """
        _response = await self._raw_client.run_processor(
            processor_id=processor_id,
            file=file,
            raw_text=raw_text,
            version=version,
            priority=priority,
            metadata=metadata,
            config=config,
            request_options=request_options,
        )
        return _response.data

    async def get_processor_run(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetProcessorRunsIdResponse:
        """
        Retrieve details about a specific processor run, including its status, outputs, and any edits made during review

        Parameters
        ----------
        id : str
            The unique identifier of the processor run to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProcessorRunsIdResponse
            Successfully retrieved processor run

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.processor_endpoints.get_processor_run(id='id', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_processor_run(id, request_options=request_options)
        return _response.data

    async def create_processor(
        self,
        *,
        name: str,
        type: ProcessorType,
        clone_processor_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostProcessorsResponse:
        """
        Create a new processor in Extend, optionally cloning from an existing processor

        Parameters
        ----------
        name : str
            The name of the new processor

        type : ProcessorType

        clone_processor_id : typing.Optional[str]
            The ID of an existing processor to clone. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostProcessorsResponse
            Successfully created processor

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.processor_endpoints.create_processor(name='name', type="EXTRACT", )
        asyncio.run(main())
        """
        _response = await self._raw_client.create_processor(
            name=name, type=type, clone_processor_id=clone_processor_id, request_options=request_options
        )
        return _response.data

    async def get_processor_version(
        self, processor_id: str, processor_version_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetProcessorsProcessorIdVersionsProcessorVersionIdResponse:
        """
        Retrieve a specific version of a processor in Extend

        Parameters
        ----------
        processor_id : str
            The ID of the processor. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        processor_version_id : str
            The ID of the specific processor version to retrieve. The ID will start with "dpv_".

            Example: `"dpv_QYk6jgHA_8CsO8rVWhyNC"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProcessorsProcessorIdVersionsProcessorVersionIdResponse
            Successfully retrieved processor version

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.processor_endpoints.get_processor_version(processor_id='processorId', processor_version_id='processorVersionId', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_processor_version(
            processor_id, processor_version_id, request_options=request_options
        )
        return _response.data

    async def list_processor_versions(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetProcessorsIdVersionsResponse:
        """
        Retrieve all versions of a specific processor in Extend, including the current draft version

        Parameters
        ----------
        id : str
            The ID of the processor to retrieve versions for. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProcessorsIdVersionsResponse
            Successfully retrieved processor versions

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.processor_endpoints.list_processor_versions(id='id', )
        asyncio.run(main())
        """
        _response = await self._raw_client.list_processor_versions(id, request_options=request_options)
        return _response.data

    async def publish_processor_version(
        self,
        id: str,
        *,
        release_type: PostProcessorsIdPublishRequestReleaseType,
        description: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostProcessorsIdPublishResponse:
        """
        Publish a new version of an existing processor in Extend

        Parameters
        ----------
        id : str
            The ID of the processor to publish a new version for. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        release_type : PostProcessorsIdPublishRequestReleaseType
            The type of release for this version

        description : typing.Optional[str]
            A description of the changes in this version

        config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Optionally supply a config object for this version of the processor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostProcessorsIdPublishResponse
            Successfully published processor version

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.processor_endpoints.publish_processor_version(id='id', release_type="major", )
        asyncio.run(main())
        """
        _response = await self._raw_client.publish_processor_version(
            id, release_type=release_type, description=description, config=config, request_options=request_options
        )
        return _response.data

    async def get_batch_processor_run(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetBatchProcessorRunsIdResponse:
        """
        Retrieve details about a batch processor run, including evaluation runs

        Parameters
        ----------
        id : str
            The unique identifier of the batch processor run to retrieve. The ID will start with "bpr_".

            Example: `"bpr_Xj8mK2pL9nR4vT7qY5wZ"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBatchProcessorRunsIdResponse
            Successfully retrieved batch processor run

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.processor_endpoints.get_batch_processor_run(id='id', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_batch_processor_run(id, request_options=request_options)
        return _response.data

    async def update_processor(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostProcessorsIdResponse:
        """
        Update an existing processor in Extend

        Parameters
        ----------
        id : str
            The ID of the processor to update. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        name : typing.Optional[str]
            The new name for the processor

        config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            The new configuration for the processor

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostProcessorsIdResponse
            Successfully updated processor

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.processor_endpoints.update_processor(id='id', )
        asyncio.run(main())
        """
        _response = await self._raw_client.update_processor(
            id, name=name, config=config, request_options=request_options
        )
        return _response.data
