# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_parse_request_config_advanced_options import PostParseRequestConfigAdvancedOptions
from .post_parse_request_config_block_options import PostParseRequestConfigBlockOptions
from .post_parse_request_config_chunking_strategy import PostParseRequestConfigChunkingStrategy
from .post_parse_request_config_target import PostParseRequestConfigTarget


class PostParseRequestConfig(UniversalBaseModel):
    target: typing.Optional[PostParseRequestConfigTarget] = pydantic.Field(default=None)
    """
    The target format for the parsed content
    """

    chunking_strategy: typing_extensions.Annotated[
        typing.Optional[PostParseRequestConfigChunkingStrategy], FieldMetadata(alias="chunkingStrategy")
    ] = None
    block_options: typing_extensions.Annotated[
        typing.Optional[PostParseRequestConfigBlockOptions], FieldMetadata(alias="blockOptions")
    ] = None
    advanced_options: typing_extensions.Annotated[
        typing.Optional[PostParseRequestConfigAdvancedOptions], FieldMetadata(alias="advancedOptions")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
