# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_parse_request_config_chunking_strategy_type import PostParseRequestConfigChunkingStrategyType


class PostParseRequestConfigChunkingStrategy(UniversalBaseModel):
    type: typing.Optional[PostParseRequestConfigChunkingStrategyType] = pydantic.Field(default=None)
    """
    The type of chunking strategy
    """

    min_characters: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="minCharacters")] = (
        pydantic.Field(default=None)
    )
    """
    Minimum number of characters per chunk
    """

    max_characters: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="maxCharacters")] = (
        pydantic.Field(default=None)
    )
    """
    Maximum number of characters per chunk
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
