# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_parse_request_config_block_options_figures import PostParseRequestConfigBlockOptionsFigures
from .post_parse_request_config_block_options_tables import PostParseRequestConfigBlockOptionsTables
from .post_parse_request_config_block_options_text import PostParseRequestConfigBlockOptionsText


class PostParseRequestConfigBlockOptions(UniversalBaseModel):
    figures: typing.Optional[PostParseRequestConfigBlockOptionsFigures] = None
    tables: typing.Optional[PostParseRequestConfigBlockOptionsTables] = None
    text: typing.Optional[PostParseRequestConfigBlockOptionsText] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
