# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.file4 import File4
from ..types.max_page_size import MaxPageSize
from ..types.next_page_token import NextPageToken
from ..types.sort_by_enum import SortByEnum
from ..types.sort_dir_enum import SortDirEnum
from ..types.workflow_status import WorkflowStatus
from .raw_client import AsyncRawWorkflowEndpointsClient, RawWorkflowEndpointsClient
from .types.get_workflow_runs_response import GetWorkflowRunsResponse
from .types.get_workflow_runs_workflow_run_id_response import GetWorkflowRunsWorkflowRunIdResponse
from .types.post_workflow_runs_response import PostWorkflowRunsResponse
from .types.post_workflow_runs_workflow_run_id_outputs_output_id_response import (
    PostWorkflowRunsWorkflowRunIdOutputsOutputIdResponse,
)
from .types.post_workflows_response import PostWorkflowsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WorkflowEndpointsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWorkflowEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWorkflowEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWorkflowEndpointsClient
        """
        return self._raw_client

    def list_workflow_runs(
        self,
        *,
        status: typing.Optional[WorkflowStatus] = None,
        workflow_id: typing.Optional[str] = None,
        file_name_contains: typing.Optional[str] = None,
        sort_by: typing.Optional[SortByEnum] = None,
        sort_dir: typing.Optional[SortDirEnum] = None,
        next_page_token: typing.Optional[NextPageToken] = None,
        max_page_size: typing.Optional[MaxPageSize] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetWorkflowRunsResponse:
        """
        List runs of a Workflow. Workflows are sequences of steps that process files and data in a specific order to achieve a desired outcome. A WorkflowRun represents a single execution of a workflow against a file.

        Parameters
        ----------
        status : typing.Optional[WorkflowStatus]
            Filters workflow runs by their status. If not provided, no filter is applied.

             The status of a workflow run:
             * `"PENDING"` - The workflow run has not started yet
             * `"PROCESSING"` - The workflow run is in progress
             * `"NEEDS_REVIEW"` - The workflow run requires manual review
             * `"REJECTED"` - The workflow run was rejected during manual review
             * `"PROCESSED"` - The workflow run completed successfully
             * `"FAILED"` - The workflow run encountered an error

        workflow_id : typing.Optional[str]
            Filters workflow runs by the workflow ID. If not provided, runs for all workflows are returned. The ID will start with "workflow". This ID can be found when viewing a workflow on the Extend platform.

            Example: `"workflow_BMdfq_yWM3sT-ZzvCnA3f"`

        file_name_contains : typing.Optional[str]
            Filters workflow runs by the name of the file. Only returns workflow runs where the file name contains this string.

            Example: `"invoice"`

        sort_by : typing.Optional[SortByEnum]
            Sorts the workflow runs by the given field.

        sort_dir : typing.Optional[SortDirEnum]
            Sorts the workflow runs in ascending or descending order. Ascending order means the earliest workflow run is returned first.

        next_page_token : typing.Optional[NextPageToken]

        max_page_size : typing.Optional[MaxPageSize]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWorkflowRunsResponse
            You will get a list of summaries for each workflow run. These are shortened versions of the full WorkflowRun object. See [The Workflow Run Summary object](/developers/objects/workflow-run-summary) for more details.

            To get the full object, use the [Get WorkflowRun](/developers/api-reference/workflow-endpoints/get-workflow-run) endpoint.

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.workflow_endpoints.list_workflow_runs()
        """
        _response = self._raw_client.list_workflow_runs(
            status=status,
            workflow_id=workflow_id,
            file_name_contains=file_name_contains,
            sort_by=sort_by,
            sort_dir=sort_dir,
            next_page_token=next_page_token,
            max_page_size=max_page_size,
            request_options=request_options,
        )
        return _response.data

    def run_workflow(
        self,
        *,
        workflow_id: str,
        files: typing.Optional[typing.Sequence[File4]] = OMIT,
        raw_texts: typing.Optional[typing.Sequence[str]] = OMIT,
        version: typing.Optional[str] = OMIT,
        priority: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostWorkflowRunsResponse:
        """
        Run a Workflow with files. A Workflow is a sequence of steps that process files and data in a specific order to achieve a desired outcome. A WorkflowRun will be created for each file processed. A WorkflowRun represents a single execution of a workflow against a file.

        Parameters
        ----------
        workflow_id : str
            The ID of the workflow to run. The ID will start with "workflow". This ID can be found viewing the workflow on the Extend platform.

            Example: `"workflow_BMdfq_yWM3sT-ZzvCnA3f"`

        files : typing.Optional[typing.Sequence[File4]]
            An array of files to process through the workflow. Either the `files` array or `rawTexts` array must be provided. Supported file types can be found [here](/developers/guides/supported-file-types).

        raw_texts : typing.Optional[typing.Sequence[str]]
            An array of raw strings. Can be used in place of files when passing raw data. The raw data will be converted to `.txt` files and run through the workflow. If the data follows a specific format, it is recommended to use the files parameter instead. Either `files` or `rawTexts` must be provided.

        version : typing.Optional[str]
            An optional version of the workflow that files will be run through. This number can be found when viewing the workflow on the Extend platform. When a version number is not supplied, the most recent version of the workflow will be used. To run the `"draft"` version of a workflow, use `"draft"` as the version.

            Examples:
            - `"3"` - Run version 3 of the workflow
            - `"draft"` - Run the draft version of the workflow

        priority : typing.Optional[int]
            An optional value used to determine the relative order of WorkflowRuns when rate limiting is in effect. Lower values will be prioritized before higher values.

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            A optional metadata object that can be assigned to a specific WorkflowRun to help identify it. It will be returned in the response and webhooks. You can place any arbitrary `key : value` pairs in this object.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostWorkflowRunsResponse
            Successfully created workflow runs

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.workflow_endpoints.run_workflow(workflow_id='workflowId', )
        """
        _response = self._raw_client.run_workflow(
            workflow_id=workflow_id,
            files=files,
            raw_texts=raw_texts,
            version=version,
            priority=priority,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def get_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetWorkflowRunsWorkflowRunIdResponse:
        """
        Once a workflow has been run, you can check the status and output of a specific WorkflowRun.

        Parameters
        ----------
        workflow_run_id : str
            The ID of the WorkflowRun that was outputted after a Workflow was run through the API. The ID will start with "workflow_run". This ID can be found when creating a WorkflowRun via API, or when viewing the "history" tab of a workflow on the Extend platform.

            Example: `"workflow_run_8k9m-xyzAB_Pqrst-Nvw4"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWorkflowRunsWorkflowRunIdResponse
            Successfully retrieved workflow run

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.workflow_endpoints.get_workflow_run(workflow_run_id='workflowRunId', )
        """
        _response = self._raw_client.get_workflow_run(workflow_run_id, request_options=request_options)
        return _response.data

    def update_workflow_run(
        self,
        workflow_run_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        You can update the name and metadata of an in progress WorkflowRun at any time using this endpoint.

        Parameters
        ----------
        workflow_run_id : str
            The ID of the WorkflowRun. This ID will start with "workflow_run". This ID can be found in the API response when creating a Workflow Run, or in the "history" tab of a workflow on the Extend platform.

            Example: `"workflow_run_8k9m-xyzAB_Pqrst-Nvw4"`

        name : typing.Optional[str]
            An optional name that can be assigned to a specific WorkflowRun

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            A metadata object that can be assigned to a specific WorkflowRun. If metadata already exists on this WorkflowRun, the newly incoming metadata will be merged with the existing metadata, with the incoming metadata taking field precedence.

            You can include any arbitrary `key : value` pairs in this object.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.workflow_endpoints.update_workflow_run(workflow_run_id='workflowRunId', )
        """
        _response = self._raw_client.update_workflow_run(
            workflow_run_id, name=name, metadata=metadata, request_options=request_options
        )
        return _response.data

    def correct_workflow_run_outputs(
        self,
        workflow_run_id: str,
        output_id: str,
        *,
        reviewed_output: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostWorkflowRunsWorkflowRunIdOutputsOutputIdResponse:
        """
        Use this endpoint to submit corrected outputs for a WorkflowRun for future processor evaluation and tuning in Extend.

        If you are using our Human-in-the-loop workflow review, then we already will be collecting your operator submitted corrections. However, if you are receiving data via the API without human review, there could be incorrect outputs that you would like to correct for future usage in evaluation and tuning within the Extend platform. This endpoint allows you to submit corrected outputs for a WorkflowRun, by providing the correct output for a given output ID.

        The output ID, would be found in a given entry within the outputs arrays of a [WorkflowRun](https://extendconfig.docs.buildwithfern.com/developers/objects/workflow-run) payload. The ID would look something like `dpr_gwkZZNRrPgkjcq0y-***`.

        Parameters
        ----------
        workflow_run_id : str
            The ID of the workflow run that included this initial output. The ID will start with "workflow_run". This ID can be found when creating a WorkflowRun via API, or in the "history" tab of a workflow on the Extend platform.

            Example: `"workflow_run_xKm9pNv3qWsY_jL2tR5Dh"`

        output_id : str
            The ID of the output that these corrections are for. The ID will start with "dpr_".

            Example: `"dpr_Xj8mK2pL9nR4vT7qY5wZ"`

        reviewed_output : typing.Dict[str, typing.Optional[typing.Any]]
            The corrected output of the processor when run against the file.

            This should be a JSON object conforming to the [output type schema](../../guides/output-types) of the given processor.

            If this is an extraction result, you can include all fields, or just the ones that were corrected, our system will handle merges/dedupes. However, if you do include a field, we assume the value included in the final reviewed value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostWorkflowRunsWorkflowRunIdOutputsOutputIdResponse
            Successfully corrected workflow run output

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.workflow_endpoints.correct_workflow_run_outputs(workflow_run_id='workflowRunId', output_id='outputId', reviewed_output={'key': 'value'
        }, )
        """
        _response = self._raw_client.correct_workflow_run_outputs(
            workflow_run_id, output_id, reviewed_output=reviewed_output, request_options=request_options
        )
        return _response.data

    def create_workflow(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostWorkflowsResponse:
        """
        Create a new workflow in Extend. Workflows are sequences of steps that process files and data in a specific order to achieve a desired outcome.

        This endpoint will create a new workflow in Extend, which can then be configured and deployed. Typically, workflows are created from our UI, however this endpoint can be used to create workflows programmatically. Configuration of the flow still needs to be done in the dashboard.

        Parameters
        ----------
        name : str
            The name of the workflow

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostWorkflowsResponse
            Successfully created workflow

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.workflow_endpoints.create_workflow(name='name', )
        """
        _response = self._raw_client.create_workflow(name=name, request_options=request_options)
        return _response.data


class AsyncWorkflowEndpointsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWorkflowEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWorkflowEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWorkflowEndpointsClient
        """
        return self._raw_client

    async def list_workflow_runs(
        self,
        *,
        status: typing.Optional[WorkflowStatus] = None,
        workflow_id: typing.Optional[str] = None,
        file_name_contains: typing.Optional[str] = None,
        sort_by: typing.Optional[SortByEnum] = None,
        sort_dir: typing.Optional[SortDirEnum] = None,
        next_page_token: typing.Optional[NextPageToken] = None,
        max_page_size: typing.Optional[MaxPageSize] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetWorkflowRunsResponse:
        """
        List runs of a Workflow. Workflows are sequences of steps that process files and data in a specific order to achieve a desired outcome. A WorkflowRun represents a single execution of a workflow against a file.

        Parameters
        ----------
        status : typing.Optional[WorkflowStatus]
            Filters workflow runs by their status. If not provided, no filter is applied.

             The status of a workflow run:
             * `"PENDING"` - The workflow run has not started yet
             * `"PROCESSING"` - The workflow run is in progress
             * `"NEEDS_REVIEW"` - The workflow run requires manual review
             * `"REJECTED"` - The workflow run was rejected during manual review
             * `"PROCESSED"` - The workflow run completed successfully
             * `"FAILED"` - The workflow run encountered an error

        workflow_id : typing.Optional[str]
            Filters workflow runs by the workflow ID. If not provided, runs for all workflows are returned. The ID will start with "workflow". This ID can be found when viewing a workflow on the Extend platform.

            Example: `"workflow_BMdfq_yWM3sT-ZzvCnA3f"`

        file_name_contains : typing.Optional[str]
            Filters workflow runs by the name of the file. Only returns workflow runs where the file name contains this string.

            Example: `"invoice"`

        sort_by : typing.Optional[SortByEnum]
            Sorts the workflow runs by the given field.

        sort_dir : typing.Optional[SortDirEnum]
            Sorts the workflow runs in ascending or descending order. Ascending order means the earliest workflow run is returned first.

        next_page_token : typing.Optional[NextPageToken]

        max_page_size : typing.Optional[MaxPageSize]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWorkflowRunsResponse
            You will get a list of summaries for each workflow run. These are shortened versions of the full WorkflowRun object. See [The Workflow Run Summary object](/developers/objects/workflow-run-summary) for more details.

            To get the full object, use the [Get WorkflowRun](/developers/api-reference/workflow-endpoints/get-workflow-run) endpoint.

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.workflow_endpoints.list_workflow_runs()
        asyncio.run(main())
        """
        _response = await self._raw_client.list_workflow_runs(
            status=status,
            workflow_id=workflow_id,
            file_name_contains=file_name_contains,
            sort_by=sort_by,
            sort_dir=sort_dir,
            next_page_token=next_page_token,
            max_page_size=max_page_size,
            request_options=request_options,
        )
        return _response.data

    async def run_workflow(
        self,
        *,
        workflow_id: str,
        files: typing.Optional[typing.Sequence[File4]] = OMIT,
        raw_texts: typing.Optional[typing.Sequence[str]] = OMIT,
        version: typing.Optional[str] = OMIT,
        priority: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostWorkflowRunsResponse:
        """
        Run a Workflow with files. A Workflow is a sequence of steps that process files and data in a specific order to achieve a desired outcome. A WorkflowRun will be created for each file processed. A WorkflowRun represents a single execution of a workflow against a file.

        Parameters
        ----------
        workflow_id : str
            The ID of the workflow to run. The ID will start with "workflow". This ID can be found viewing the workflow on the Extend platform.

            Example: `"workflow_BMdfq_yWM3sT-ZzvCnA3f"`

        files : typing.Optional[typing.Sequence[File4]]
            An array of files to process through the workflow. Either the `files` array or `rawTexts` array must be provided. Supported file types can be found [here](/developers/guides/supported-file-types).

        raw_texts : typing.Optional[typing.Sequence[str]]
            An array of raw strings. Can be used in place of files when passing raw data. The raw data will be converted to `.txt` files and run through the workflow. If the data follows a specific format, it is recommended to use the files parameter instead. Either `files` or `rawTexts` must be provided.

        version : typing.Optional[str]
            An optional version of the workflow that files will be run through. This number can be found when viewing the workflow on the Extend platform. When a version number is not supplied, the most recent version of the workflow will be used. To run the `"draft"` version of a workflow, use `"draft"` as the version.

            Examples:
            - `"3"` - Run version 3 of the workflow
            - `"draft"` - Run the draft version of the workflow

        priority : typing.Optional[int]
            An optional value used to determine the relative order of WorkflowRuns when rate limiting is in effect. Lower values will be prioritized before higher values.

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            A optional metadata object that can be assigned to a specific WorkflowRun to help identify it. It will be returned in the response and webhooks. You can place any arbitrary `key : value` pairs in this object.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostWorkflowRunsResponse
            Successfully created workflow runs

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.workflow_endpoints.run_workflow(workflow_id='workflowId', )
        asyncio.run(main())
        """
        _response = await self._raw_client.run_workflow(
            workflow_id=workflow_id,
            files=files,
            raw_texts=raw_texts,
            version=version,
            priority=priority,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def get_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetWorkflowRunsWorkflowRunIdResponse:
        """
        Once a workflow has been run, you can check the status and output of a specific WorkflowRun.

        Parameters
        ----------
        workflow_run_id : str
            The ID of the WorkflowRun that was outputted after a Workflow was run through the API. The ID will start with "workflow_run". This ID can be found when creating a WorkflowRun via API, or when viewing the "history" tab of a workflow on the Extend platform.

            Example: `"workflow_run_8k9m-xyzAB_Pqrst-Nvw4"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWorkflowRunsWorkflowRunIdResponse
            Successfully retrieved workflow run

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.workflow_endpoints.get_workflow_run(workflow_run_id='workflowRunId', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_workflow_run(workflow_run_id, request_options=request_options)
        return _response.data

    async def update_workflow_run(
        self,
        workflow_run_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        You can update the name and metadata of an in progress WorkflowRun at any time using this endpoint.

        Parameters
        ----------
        workflow_run_id : str
            The ID of the WorkflowRun. This ID will start with "workflow_run". This ID can be found in the API response when creating a Workflow Run, or in the "history" tab of a workflow on the Extend platform.

            Example: `"workflow_run_8k9m-xyzAB_Pqrst-Nvw4"`

        name : typing.Optional[str]
            An optional name that can be assigned to a specific WorkflowRun

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            A metadata object that can be assigned to a specific WorkflowRun. If metadata already exists on this WorkflowRun, the newly incoming metadata will be merged with the existing metadata, with the incoming metadata taking field precedence.

            You can include any arbitrary `key : value` pairs in this object.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.workflow_endpoints.update_workflow_run(workflow_run_id='workflowRunId', )
        asyncio.run(main())
        """
        _response = await self._raw_client.update_workflow_run(
            workflow_run_id, name=name, metadata=metadata, request_options=request_options
        )
        return _response.data

    async def correct_workflow_run_outputs(
        self,
        workflow_run_id: str,
        output_id: str,
        *,
        reviewed_output: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostWorkflowRunsWorkflowRunIdOutputsOutputIdResponse:
        """
        Use this endpoint to submit corrected outputs for a WorkflowRun for future processor evaluation and tuning in Extend.

        If you are using our Human-in-the-loop workflow review, then we already will be collecting your operator submitted corrections. However, if you are receiving data via the API without human review, there could be incorrect outputs that you would like to correct for future usage in evaluation and tuning within the Extend platform. This endpoint allows you to submit corrected outputs for a WorkflowRun, by providing the correct output for a given output ID.

        The output ID, would be found in a given entry within the outputs arrays of a [WorkflowRun](https://extendconfig.docs.buildwithfern.com/developers/objects/workflow-run) payload. The ID would look something like `dpr_gwkZZNRrPgkjcq0y-***`.

        Parameters
        ----------
        workflow_run_id : str
            The ID of the workflow run that included this initial output. The ID will start with "workflow_run". This ID can be found when creating a WorkflowRun via API, or in the "history" tab of a workflow on the Extend platform.

            Example: `"workflow_run_xKm9pNv3qWsY_jL2tR5Dh"`

        output_id : str
            The ID of the output that these corrections are for. The ID will start with "dpr_".

            Example: `"dpr_Xj8mK2pL9nR4vT7qY5wZ"`

        reviewed_output : typing.Dict[str, typing.Optional[typing.Any]]
            The corrected output of the processor when run against the file.

            This should be a JSON object conforming to the [output type schema](../../guides/output-types) of the given processor.

            If this is an extraction result, you can include all fields, or just the ones that were corrected, our system will handle merges/dedupes. However, if you do include a field, we assume the value included in the final reviewed value.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostWorkflowRunsWorkflowRunIdOutputsOutputIdResponse
            Successfully corrected workflow run output

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.workflow_endpoints.correct_workflow_run_outputs(workflow_run_id='workflowRunId', output_id='outputId', reviewed_output={'key': 'value'
            }, )
        asyncio.run(main())
        """
        _response = await self._raw_client.correct_workflow_run_outputs(
            workflow_run_id, output_id, reviewed_output=reviewed_output, request_options=request_options
        )
        return _response.data

    async def create_workflow(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostWorkflowsResponse:
        """
        Create a new workflow in Extend. Workflows are sequences of steps that process files and data in a specific order to achieve a desired outcome.

        This endpoint will create a new workflow in Extend, which can then be configured and deployed. Typically, workflows are created from our UI, however this endpoint can be used to create workflows programmatically. Configuration of the flow still needs to be done in the dashboard.

        Parameters
        ----------
        name : str
            The name of the workflow

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostWorkflowsResponse
            Successfully created workflow

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.workflow_endpoints.create_workflow(name='name', )
        asyncio.run(main())
        """
        _response = await self._raw_client.create_workflow(name=name, request_options=request_options)
        return _response.data
