# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .batch_processor_run_options import BatchProcessorRunOptions
from .batch_processor_run_status import BatchProcessorRunStatus


class BatchProcessorRun(UniversalBaseModel):
    object: typing.Optional[str] = None
    id: typing.Optional[str] = None
    processor_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="processorId")] = None
    processor_version_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="processorVersionId")
    ] = None
    processor_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="processorName")] = None
    metrics: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    status: typing.Optional[BatchProcessorRunStatus] = None
    source: typing.Optional[typing.Literal["EVAL_SET"]] = None
    source_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="sourceId")] = None
    run_count: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="runCount")] = None
    options: typing.Optional[BatchProcessorRunOptions] = None
    created_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdAt")] = None
    updated_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="updatedAt")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
