# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .block_metadata import BlockMetadata
from .block_type import BlockType


class Block(UniversalBaseModel):
    object: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of object. In this case, it will always be `"block"`.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique identifier for the block.
    """

    type: typing.Optional[BlockType] = pydantic.Field(default=None)
    """
    The type of block:
    * `"text"` - Regular text content
    * `"heading"` - Section or document headings
    * `"section_heading"` - Subsection headings
    * `"table"` - Tabular data with rows and columns
    * `"figure"` - Images, charts, or diagrams
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    The textual content of the block.
    """

    details: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Additional details specific to the block type.
    """

    metadata: typing.Optional[BlockMetadata] = pydantic.Field(default=None)
    """
    Metadata about the block.
    """

    polygon: typing.Optional[typing.List[typing.Dict[str, typing.Optional[typing.Any]]]] = pydantic.Field(default=None)
    """
    An array of points defining the polygon that bounds the block.
    """

    bounding_box: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]], FieldMetadata(alias="boundingBox")
    ] = pydantic.Field(default=None)
    """
    A simplified bounding box for the block.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
