# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .block import Block
from .chunk_metadata import ChunkMetadata


class Chunk(UniversalBaseModel):
    object: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of object. In this case, it will always be `"chunk"`.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of chunk (e.g., "page").
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    The textual content of the chunk in the specified target format.
    """

    metadata: typing.Optional[ChunkMetadata] = pydantic.Field(default=None)
    """
    Metadata about the chunk.
    """

    blocks: typing.Optional[typing.List[Block]] = pydantic.Field(default=None)
    """
    An array of block objects that make up the chunk. See the Block object documentation for more detailed information about block structure and types.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
