# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class File4OutputsItem(UniversalBaseModel):
    processor_id: typing_extensions.Annotated[str, FieldMetadata(alias="processorId")] = pydantic.Field()
    """
    The ID of the processor that the output is associated with. The ID will start with "dp_".
    
    Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`
    """

    output: typing.Dict[str, typing.Optional[typing.Any]] = pydantic.Field()
    """
    The output that is being overridden. There are multiple types of outputs, and more details can be found [here](../../guides/output-types).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
