# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FileMetadataParentSplit(UniversalBaseModel):
    """
    The split metadata details. Only included if this file is a derivative of another file, for instance if it was created via a Splitter in a workflow.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the split.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of the split.
    """

    identifier: typing.Optional[str] = pydantic.Field(default=None)
    """
    The identifier of the split.
    """

    start_page: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="startPage")] = pydantic.Field(
        default=None
    )
    """
    The start page of the split.
    """

    end_page: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="endPage")] = pydantic.Field(
        default=None
    )
    """
    The end page of the split.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
