# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FileContentsPagesItem(UniversalBaseModel):
    page_number: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="pageNumber")] = pydantic.Field(
        default=None
    )
    """
    The page number of this page in the document.
    """

    markdown: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cleaned and structured markdown content of the page. Available for PDF and IMG file types. Only included if the `markdown` query parameter is set to true in the endpoint request.
    """

    html: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cleaned and structured html content of the page. Available for DOCX file types (that were not auto-converted to PDFs). Only included if the `html` query parameter is set to true in the endpoint request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
