# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .chunk import Chunk
from .parsed_file_metrics import ParsedFileMetrics
from .parsed_file_status import ParsedFileStatus


class ParsedFile(UniversalBaseModel):
    object: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of object. In this case, it will always be `"parser_run"`.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the parser run. The id will start with `"parser_run_"`
    
    Example: `"parser_run_Xj8mK2pL9nR4vT7qY5wZ"`
    """

    file_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="fileId")] = pydantic.Field(
        default=None
    )
    """
    The ID of the file that was parsed. The id will start with `"file_"`
    
    Example: `"file_xK9mLPqRtN3vS8wF5hB2cQ"`
    """

    chunks: typing.Optional[typing.List[Chunk]] = None
    status: typing.Optional[ParsedFileStatus] = pydantic.Field(default=None)
    """
    The status of the parser run. Possible values:
    * `"PROCESSED"` - The file was successfully processed
    * `"FAILED"` - The processing failed (see `failureReason` for details)
    """

    failure_reason: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="failureReason")] = (
        pydantic.Field(default=None)
    )
    """
    The reason for failure if status is "FAILED". Will be null for successful runs.
    """

    config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    metrics: typing.Optional[ParsedFileMetrics] = pydantic.Field(default=None)
    """
    Metrics about the parsing process.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
