# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .processor_type import ProcessorType
from .processor_version import ProcessorVersion


class Processor(UniversalBaseModel):
    object: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of response. In this case, it will always be `"document_processor"`.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the processor. The ID will start with "dp_".
    
    Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the processor.
    
    Example: `"Invoice Processor"`
    """

    type: typing.Optional[ProcessorType] = None
    created_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdAt")] = (
        pydantic.Field(default=None)
    )
    """
    The time (in UTC) at which the processor was created. Will follow the RFC 3339 format.
    
    Example: `"2024-03-21T15:30:00Z"`
    """

    updated_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="updatedAt")] = (
        pydantic.Field(default=None)
    )
    """
    The time (in UTC) at which the processor was last updated. Will follow the RFC 3339 format.
    
    Example: `"2024-03-21T16:45:00Z"`
    """

    draft_version: typing_extensions.Annotated[
        typing.Optional[ProcessorVersion], FieldMetadata(alias="draftVersion")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
