# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .file import File
from .processor_run_status import ProcessorRunStatus


class ProcessorRun(UniversalBaseModel):
    object: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of response. In this case, it will always be `"document_processor_run"`.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier for this processor run. The ID will start with "processor_run_".
    
    Example: `"processor_run_Xj8mK2pL9nR4vT7qY5wZ"`
    """

    processor_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="processorId")] = (
        pydantic.Field(default=None)
    )
    """
    The ID of the processor used for this run. The ID will start with "dp_".
    
    Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`
    """

    processor_version_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="processorVersionId")
    ] = pydantic.Field(default=None)
    """
    The ID of the specific processor version used.
    """

    processor_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="processorName")] = (
        pydantic.Field(default=None)
    )
    """
    The name of the processor.
    
    Example: `"Invoice Processor"`
    """

    status: typing.Optional[ProcessorRunStatus] = pydantic.Field(default=None)
    """
    The current status of the processor run:
    * `"PROCESSING"` - The processor is currently running
    * `"PROCESSED"` - The processor has completed successfully
    * `"FAILED"` - The processor encountered an error
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Any metadata that was provided when creating the processor run.
    """

    reviewed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the run has been reviewed.
    """

    edited: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the run results have been edited.
    """

    edits: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Contains any edits made to the processor output. For each edited field:
    * `originalValue` - The original value before editing
    * `editedValue` - The value after editing
    * `fieldType` - The type of the field
    * `notes` - Any notes added during editing
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of processor (e.g., "EXTRACT", "CLASSIFY").
    """

    config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    The configuration used for this processor run.
    """

    initial_output: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]], FieldMetadata(alias="initialOutput")
    ] = pydantic.Field(default=None)
    """
    The initial output from the processor.
    """

    reviewed_output: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]], FieldMetadata(alias="reviewedOutput")
    ] = pydantic.Field(default=None)
    """
    The output after review, if any.
    """

    output: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    The final output, either reviewed or initial.
    
    Conforms to the shape of output types and depends on the processor type and configuration shape.
    """

    files: typing.Optional[typing.List[File]] = pydantic.Field(default=None)
    """
    Details of the processed files.
    
    If this was a file generated from a splitter processor, this will be the sub file.
    
    See the File object for more details.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
