# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawFileEndpointsClient, RawFileEndpointsClient
from .types.get_files_id_response import GetFilesIdResponse
from .types.get_files_request_sort_dir import GetFilesRequestSortDir
from .types.get_files_response import GetFilesResponse
from .types.post_evaluation_set_items_bulk_request_items_item import PostEvaluationSetItemsBulkRequestItemsItem
from .types.post_evaluation_set_items_bulk_response import PostEvaluationSetItemsBulkResponse
from .types.post_evaluation_set_items_id_response import PostEvaluationSetItemsIdResponse
from .types.post_evaluation_set_items_response import PostEvaluationSetItemsResponse
from .types.post_evaluation_sets_response import PostEvaluationSetsResponse
from .types.post_files_response import PostFilesResponse
from .types.post_files_upload_response import PostFilesUploadResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FileEndpointsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFileEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFileEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFileEndpointsClient
        """
        return self._raw_client

    def list_files(
        self,
        *,
        name_contains: typing.Optional[str] = None,
        sort_dir: typing.Optional[GetFilesRequestSortDir] = None,
        next_page_token: typing.Optional[str] = None,
        max_page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetFilesResponse:
        """
        List files in your account. Files represent documents that have been uploaded to Extend.

        Parameters
        ----------
        name_contains : typing.Optional[str]
            Filters files by the name of the file

        sort_dir : typing.Optional[GetFilesRequestSortDir]
            Sorts the files in ascending or descending order

        next_page_token : typing.Optional[str]
            The token used to fetch the page of results from a previous request. We use cursor based pagination and will return a `nextPageToken` in the response if there are more results.

            Note: If parameters other than `nextPageToken` change in subsequence requests, you are likely to receive incomplete results.

            Example: `"xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="`

        max_page_size : typing.Optional[int]
            The maximum number of results to return in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFilesResponse
            Successfully retrieved files

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.file_endpoints.list_files()
        """
        _response = self._raw_client.list_files(
            name_contains=name_contains,
            sort_dir=sort_dir,
            next_page_token=next_page_token,
            max_page_size=max_page_size,
            request_options=request_options,
        )
        return _response.data

    def create_file_deprecated(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        url: typing.Optional[str] = OMIT,
        raw_text: typing.Optional[str] = OMIT,
        media_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostFilesResponse:
        """
        Create a new file in Extend for use in an evaluation set. This endpoint is deprecated, use /files/upload instead.

        Parameters
        ----------
        name : typing.Optional[str]
            The name of the file

        url : typing.Optional[str]
            A pre signed URL for the file

        raw_text : typing.Optional[str]
            The raw text content of the file

        media_type : typing.Optional[str]
            The media type of the file (e.g. application/pdf)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostFilesResponse
            Successfully created file

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.file_endpoints.create_file_deprecated()
        """
        _response = self._raw_client.create_file_deprecated(
            name=name, url=url, raw_text=raw_text, media_type=media_type, request_options=request_options
        )
        return _response.data

    def get_file(
        self,
        id: str,
        *,
        raw_text: typing.Optional[bool] = None,
        markdown: typing.Optional[bool] = None,
        html: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetFilesIdResponse:
        """
        Fetch a file by its ID

        Parameters
        ----------
        id : str
            Extend's ID for the file. It will always start with `"file_"`.

            Example: `"file_Xj8mK2pL9nR4vT7qY5wZ"`

        raw_text : typing.Optional[bool]
            If set to true, the raw text content of the file will be included in the response. This is useful for indexing text-based files like PDFs, Word Documents, etc.

        markdown : typing.Optional[bool]
            If set to true, the markdown content of the file will be included in the response. This is useful for indexing very clean content into RAG pipelines for files like PDFs, Word Documents, etc.

            *Only available for files with a type of PDF, IMG.
            *or .doc/.docx files that were auto-converted to PDFs.

        html : typing.Optional[bool]
            If set to true, the html content of the file will be included in the response. This is useful for indexing html content into RAG pipelines for files like PDFs, Word Documents, etc.

            *Only available for files with a type of DOCX.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFilesIdResponse
            Successfully retrieved file

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.file_endpoints.get_file(id='id', )
        """
        _response = self._raw_client.get_file(
            id, raw_text=raw_text, markdown=markdown, html=html, request_options=request_options
        )
        return _response.data

    def create_evaluation_set(
        self, *, name: str, description: str, processor_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostEvaluationSetsResponse:
        """
        Create a new evaluation set in Extend

        Parameters
        ----------
        name : str
            The name of the evaluation set.

            Example: `"Invoice Processing Test Set"`

        description : str
            A description of what this evaluation set is used for.

            Example: `"Q4 2023 vendor invoices"`

        processor_id : str
            The ID of the processor to create an evaluation set for. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationSetsResponse
            Successfully created evaluation set

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.file_endpoints.create_evaluation_set(name='name', description='description', processor_id='processorId', )
        """
        _response = self._raw_client.create_evaluation_set(
            name=name, description=description, processor_id=processor_id, request_options=request_options
        )
        return _response.data

    def create_evaluation_set_item(
        self,
        *,
        evaluation_set_id: str,
        file_id: str,
        expected_output: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostEvaluationSetItemsResponse:
        """
        Create a new evaluation set item

        Parameters
        ----------
        evaluation_set_id : str
            The ID of the evaluation set to add the item to. The ID will start with "ev_".

            Example: `"ev_Xj8mK2pL9nR4vT7qY5wZ"`

        file_id : str
            Extend's internal ID for the file. It will always start with "file_".

            Example: `"file_xK9mLPqRtN3vS8wF5hB2cQ"`

        expected_output : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationSetItemsResponse
            Successfully created evaluation set item

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.file_endpoints.create_evaluation_set_item(evaluation_set_id='evaluationSetId', file_id='fileId', expected_output={'key': 'value'
        }, )
        """
        _response = self._raw_client.create_evaluation_set_item(
            evaluation_set_id=evaluation_set_id,
            file_id=file_id,
            expected_output=expected_output,
            request_options=request_options,
        )
        return _response.data

    def update_evaluation_set_item(
        self,
        id: str,
        *,
        expected_output: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostEvaluationSetItemsIdResponse:
        """
        Update an evaluation set item by ID

        Parameters
        ----------
        id : str
            The ID of the evaluation set item to update. The ID will start with "evi_".

            Example: `"evi_kR9mNP12Qw4yTv8BdR3H"`

        expected_output : typing.Dict[str, typing.Optional[typing.Any]]
            The expected output of the processor when run against the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationSetItemsIdResponse
            Successfully updated evaluation set item

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.file_endpoints.update_evaluation_set_item(id='id', expected_output={'key': 'value'
        }, )
        """
        _response = self._raw_client.update_evaluation_set_item(
            id, expected_output=expected_output, request_options=request_options
        )
        return _response.data

    def bulk_create_evaluation_set_items(
        self,
        *,
        evaluation_set_id: str,
        items: typing.Sequence[PostEvaluationSetItemsBulkRequestItemsItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostEvaluationSetItemsBulkResponse:
        """
        Create evaluation set items for a given evaluation set in bulk

        Parameters
        ----------
        evaluation_set_id : str
            The ID of the evaluation set to add the items to. The ID will start with "ev_".

            Example: `"ev_2LcgeY_mp2T5yPaEuq5Lw"`

        items : typing.Sequence[PostEvaluationSetItemsBulkRequestItemsItem]
            An array of objects representing the evaluation set items to create

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationSetItemsBulkResponse
            Successfully created evaluation set items

        Examples
        --------
        from fernstarterpack import Starter
        from fernstarterpack.file_endpoints import PostEvaluationSetItemsBulkRequestItemsItem
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.file_endpoints.bulk_create_evaluation_set_items(evaluation_set_id='evaluationSetId', items=[PostEvaluationSetItemsBulkRequestItemsItem(file_id='fileId', expected_output={'key': 'value'
        }, )], )
        """
        _response = self._raw_client.bulk_create_evaluation_set_items(
            evaluation_set_id=evaluation_set_id, items=items, request_options=request_options
        )
        return _response.data

    def upload_file(
        self, *, file: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> PostFilesUploadResponse:
        """
        Upload and create a new file in Extend

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostFilesUploadResponse
            Successfully uploaded file

        Examples
        --------
        from fernstarterpack import Starter
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.file_endpoints.upload_file()
        """
        _response = self._raw_client.upload_file(file=file, request_options=request_options)
        return _response.data


class AsyncFileEndpointsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFileEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFileEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFileEndpointsClient
        """
        return self._raw_client

    async def list_files(
        self,
        *,
        name_contains: typing.Optional[str] = None,
        sort_dir: typing.Optional[GetFilesRequestSortDir] = None,
        next_page_token: typing.Optional[str] = None,
        max_page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetFilesResponse:
        """
        List files in your account. Files represent documents that have been uploaded to Extend.

        Parameters
        ----------
        name_contains : typing.Optional[str]
            Filters files by the name of the file

        sort_dir : typing.Optional[GetFilesRequestSortDir]
            Sorts the files in ascending or descending order

        next_page_token : typing.Optional[str]
            The token used to fetch the page of results from a previous request. We use cursor based pagination and will return a `nextPageToken` in the response if there are more results.

            Note: If parameters other than `nextPageToken` change in subsequence requests, you are likely to receive incomplete results.

            Example: `"xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="`

        max_page_size : typing.Optional[int]
            The maximum number of results to return in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFilesResponse
            Successfully retrieved files

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.file_endpoints.list_files()
        asyncio.run(main())
        """
        _response = await self._raw_client.list_files(
            name_contains=name_contains,
            sort_dir=sort_dir,
            next_page_token=next_page_token,
            max_page_size=max_page_size,
            request_options=request_options,
        )
        return _response.data

    async def create_file_deprecated(
        self,
        *,
        name: typing.Optional[str] = OMIT,
        url: typing.Optional[str] = OMIT,
        raw_text: typing.Optional[str] = OMIT,
        media_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostFilesResponse:
        """
        Create a new file in Extend for use in an evaluation set. This endpoint is deprecated, use /files/upload instead.

        Parameters
        ----------
        name : typing.Optional[str]
            The name of the file

        url : typing.Optional[str]
            A pre signed URL for the file

        raw_text : typing.Optional[str]
            The raw text content of the file

        media_type : typing.Optional[str]
            The media type of the file (e.g. application/pdf)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostFilesResponse
            Successfully created file

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.file_endpoints.create_file_deprecated()
        asyncio.run(main())
        """
        _response = await self._raw_client.create_file_deprecated(
            name=name, url=url, raw_text=raw_text, media_type=media_type, request_options=request_options
        )
        return _response.data

    async def get_file(
        self,
        id: str,
        *,
        raw_text: typing.Optional[bool] = None,
        markdown: typing.Optional[bool] = None,
        html: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetFilesIdResponse:
        """
        Fetch a file by its ID

        Parameters
        ----------
        id : str
            Extend's ID for the file. It will always start with `"file_"`.

            Example: `"file_Xj8mK2pL9nR4vT7qY5wZ"`

        raw_text : typing.Optional[bool]
            If set to true, the raw text content of the file will be included in the response. This is useful for indexing text-based files like PDFs, Word Documents, etc.

        markdown : typing.Optional[bool]
            If set to true, the markdown content of the file will be included in the response. This is useful for indexing very clean content into RAG pipelines for files like PDFs, Word Documents, etc.

            *Only available for files with a type of PDF, IMG.
            *or .doc/.docx files that were auto-converted to PDFs.

        html : typing.Optional[bool]
            If set to true, the html content of the file will be included in the response. This is useful for indexing html content into RAG pipelines for files like PDFs, Word Documents, etc.

            *Only available for files with a type of DOCX.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFilesIdResponse
            Successfully retrieved file

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.file_endpoints.get_file(id='id', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_file(
            id, raw_text=raw_text, markdown=markdown, html=html, request_options=request_options
        )
        return _response.data

    async def create_evaluation_set(
        self, *, name: str, description: str, processor_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostEvaluationSetsResponse:
        """
        Create a new evaluation set in Extend

        Parameters
        ----------
        name : str
            The name of the evaluation set.

            Example: `"Invoice Processing Test Set"`

        description : str
            A description of what this evaluation set is used for.

            Example: `"Q4 2023 vendor invoices"`

        processor_id : str
            The ID of the processor to create an evaluation set for. The ID will start with "dp_".

            Example: `"dp_Xj8mK2pL9nR4vT7qY5wZ"`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationSetsResponse
            Successfully created evaluation set

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.file_endpoints.create_evaluation_set(name='name', description='description', processor_id='processorId', )
        asyncio.run(main())
        """
        _response = await self._raw_client.create_evaluation_set(
            name=name, description=description, processor_id=processor_id, request_options=request_options
        )
        return _response.data

    async def create_evaluation_set_item(
        self,
        *,
        evaluation_set_id: str,
        file_id: str,
        expected_output: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostEvaluationSetItemsResponse:
        """
        Create a new evaluation set item

        Parameters
        ----------
        evaluation_set_id : str
            The ID of the evaluation set to add the item to. The ID will start with "ev_".

            Example: `"ev_Xj8mK2pL9nR4vT7qY5wZ"`

        file_id : str
            Extend's internal ID for the file. It will always start with "file_".

            Example: `"file_xK9mLPqRtN3vS8wF5hB2cQ"`

        expected_output : typing.Dict[str, typing.Optional[typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationSetItemsResponse
            Successfully created evaluation set item

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.file_endpoints.create_evaluation_set_item(evaluation_set_id='evaluationSetId', file_id='fileId', expected_output={'key': 'value'
            }, )
        asyncio.run(main())
        """
        _response = await self._raw_client.create_evaluation_set_item(
            evaluation_set_id=evaluation_set_id,
            file_id=file_id,
            expected_output=expected_output,
            request_options=request_options,
        )
        return _response.data

    async def update_evaluation_set_item(
        self,
        id: str,
        *,
        expected_output: typing.Dict[str, typing.Optional[typing.Any]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostEvaluationSetItemsIdResponse:
        """
        Update an evaluation set item by ID

        Parameters
        ----------
        id : str
            The ID of the evaluation set item to update. The ID will start with "evi_".

            Example: `"evi_kR9mNP12Qw4yTv8BdR3H"`

        expected_output : typing.Dict[str, typing.Optional[typing.Any]]
            The expected output of the processor when run against the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationSetItemsIdResponse
            Successfully updated evaluation set item

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.file_endpoints.update_evaluation_set_item(id='id', expected_output={'key': 'value'
            }, )
        asyncio.run(main())
        """
        _response = await self._raw_client.update_evaluation_set_item(
            id, expected_output=expected_output, request_options=request_options
        )
        return _response.data

    async def bulk_create_evaluation_set_items(
        self,
        *,
        evaluation_set_id: str,
        items: typing.Sequence[PostEvaluationSetItemsBulkRequestItemsItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostEvaluationSetItemsBulkResponse:
        """
        Create evaluation set items for a given evaluation set in bulk

        Parameters
        ----------
        evaluation_set_id : str
            The ID of the evaluation set to add the items to. The ID will start with "ev_".

            Example: `"ev_2LcgeY_mp2T5yPaEuq5Lw"`

        items : typing.Sequence[PostEvaluationSetItemsBulkRequestItemsItem]
            An array of objects representing the evaluation set items to create

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationSetItemsBulkResponse
            Successfully created evaluation set items

        Examples
        --------
        from fernstarterpack import AsyncStarter
        from fernstarterpack.file_endpoints import PostEvaluationSetItemsBulkRequestItemsItem
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.file_endpoints.bulk_create_evaluation_set_items(evaluation_set_id='evaluationSetId', items=[PostEvaluationSetItemsBulkRequestItemsItem(file_id='fileId', expected_output={'key': 'value'
            }, )], )
        asyncio.run(main())
        """
        _response = await self._raw_client.bulk_create_evaluation_set_items(
            evaluation_set_id=evaluation_set_id, items=items, request_options=request_options
        )
        return _response.data

    async def upload_file(
        self, *, file: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> PostFilesUploadResponse:
        """
        Upload and create a new file in Extend

        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostFilesUploadResponse
            Successfully uploaded file

        Examples
        --------
        from fernstarterpack import AsyncStarter
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.file_endpoints.upload_file()
        asyncio.run(main())
        """
        _response = await self._raw_client.upload_file(file=file, request_options=request_options)
        return _response.data
