# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawParseEndpointsClient, RawParseEndpointsClient
from .types.post_parse_request_config import PostParseRequestConfig
from .types.post_parse_request_file import PostParseRequestFile
from .types.post_parse_response import PostParseResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ParseEndpointsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawParseEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawParseEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawParseEndpointsClient
        """
        return self._raw_client

    def parse_file(
        self,
        *,
        file: PostParseRequestFile,
        config: PostParseRequestConfig,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostParseResponse:
        """
        Parse files to get cleaned, chunked target content (e.g. markdown)

        Parameters
        ----------
        file : PostParseRequestFile

        config : PostParseRequestConfig

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostParseResponse
            Successfully parsed file

        Examples
        --------
        from fernstarterpack import Starter
        from fernstarterpack.parse_endpoints import PostParseRequestFile
        from fernstarterpack.parse_endpoints import PostParseRequestConfig
        client = Starter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        client.parse_endpoints.parse_file(file=PostParseRequestFile(), config=PostParseRequestConfig(), )
        """
        _response = self._raw_client.parse_file(file=file, config=config, request_options=request_options)
        return _response.data


class AsyncParseEndpointsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawParseEndpointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawParseEndpointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawParseEndpointsClient
        """
        return self._raw_client

    async def parse_file(
        self,
        *,
        file: PostParseRequestFile,
        config: PostParseRequestConfig,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostParseResponse:
        """
        Parse files to get cleaned, chunked target content (e.g. markdown)

        Parameters
        ----------
        file : PostParseRequestFile

        config : PostParseRequestConfig

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostParseResponse
            Successfully parsed file

        Examples
        --------
        from fernstarterpack import AsyncStarter
        from fernstarterpack.parse_endpoints import PostParseRequestFile
        from fernstarterpack.parse_endpoints import PostParseRequestConfig
        import asyncio
        client = AsyncStarter(extend_api_version="YOUR_EXTEND_API_VERSION", token="YOUR_TOKEN", )
        async def main() -> None:
            await client.parse_endpoints.parse_file(file=PostParseRequestFile(), config=PostParseRequestConfig(), )
        asyncio.run(main())
        """
        _response = await self._raw_client.parse_file(file=file, config=config, request_options=request_options)
        return _response.data
