# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.workflow_run import WorkflowRun


class GetWorkflowRunsWorkflowRunIdResponse(UniversalBaseModel):
    success: typing.Optional[bool] = None
    workflow_run: typing_extensions.Annotated[typing.Optional[WorkflowRun], FieldMetadata(alias="workflowRun")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
