# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.workflow_run_summary import WorkflowRunSummary


class GetWorkflowRunsResponse(UniversalBaseModel):
    success: typing.Optional[bool] = None
    workflow_runs: typing_extensions.Annotated[
        typing.Optional[typing.List[WorkflowRunSummary]], FieldMetadata(alias="workflowRuns")
    ] = None
    next_page_token: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="nextPageToken")] = (
        pydantic.Field(default=None)
    )
    """
    The token used to fetch the next page of results. Will not be included in the response if there are no more pages to fetch.
    
    Example: `"xK9mLPqRtN3vS8wF5hB2cQ==:zWvUxYjM4nKpL7aDgE9HbTcR2mAyX3/Q+CNkfBSw1dZ="`
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
