# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.workflow_run import WorkflowRun


class PostWorkflowRunsResponse(UniversalBaseModel):
    success: typing.Optional[bool] = None
    workflow_runs: typing_extensions.Annotated[
        typing.Optional[typing.List[WorkflowRun]], FieldMetadata(alias="workflowRuns")
    ] = pydantic.Field(default=None)
    """
    An array of WorkflowRun objects, with each WorkflowRun corresponding to a single File that was passed in.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
